name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build exercise-1
        working-directory: ./exercise-1
        run: |
          export docker_image_name="$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)"
          echo "$docker_image_name">> $GITHUB_ENV
          export docker_image_tag="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          echo "$docker_image_tag">> $GITHUB_ENV
          docker build . --file Dockerfile --tag "$docker_image_name:$docker_image_tag" --build-arg="app=$docker_image_name" --build-arg="version=$docker_image_tag"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          echo tag_with_timestamp="${{ vars.DOCKERHUB_USERNAME }}/${{ env.docker_image_name }}:${{ env.docker_image_tag }}-$(date +%s)" >> $GITHUB_ENV
          docker tag "${{ env.docker_image_name }}:${{ env.docker_image_tag }}" "${{ env.tag_with_timestamp }}"
          docker push "${{ env.tag_with_timestamp }}"